# Generated by Django 4.0.2 on 2022-02-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikepost',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
