# Generated by Django 4.0.2 on 2022-02-24 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_bikepost_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikepost',
            name='post_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
