# Generated by Django 4.0.2 on 2022-03-14 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_bikepost_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentbike',
            name='rent_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
        ),
    ]
