# Generated by Django 4.0.2 on 2022-03-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_rentbike_rent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentbike',
            name='delivery_status',
            field=models.CharField(default='Not Return', max_length=30),
        ),
    ]
