# Generated by Django 4.0.2 on 2022-02-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_bikepost_post_user_alter_rentbike_rent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikepost',
            name='bike_condition',
            field=models.CharField(blank=True, choices=[('Old', 'Old'), ('Average', 'Average'), ('New', 'New')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bikepost',
            name='milagePerliter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bikepost',
            name='milage_covered',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
