# Generated by Django 4.0.2 on 2022-02-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_bikepost_bike_condition_bikepost_milageperliter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikepost',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
